name: Dev-Publish

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          npm ci
          node ./createDevManifest
          npm run build:dev
          
      - name: Publish
        run: |
          npm run publish-dev -- --token $TOKEN
        env:
          TOKEN: ${{ secrets.PUBLISH_PAT }}
